# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
    alpine_executor:
        working_directory: ~/app
        environment:
            DIST_DIR: public
        docker:
            - image: alpine/latest

jobs:
    build:
        executor: alpine_executor
        steps:
            - checkout
            - run: apk add cmake
