# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  alpine_executor:
    working_directory: ~/app
    environment:
      DIST_DIR: public
    docker:
      - image: alpine
        auth: 
          username: upnt
          password: $DOCKERHUB_PASSWORD

jobs:
  build:
    executor: alpine_executor
    steps:
      - checkout
      - run: apk add cmake make g++ git
      - run: git submodule init
      - run: git submodule update
      - run: cmake -G "Unix Makefiles" .
      - run: make
  test:
    executor: alpine_executor
    steps:
      - checkout
      - run: ls
      - run: make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
    
